### ISSUE TITLE
Update Homebrew Cask URL

### ISSUE THREAD

**Issue by reitermarkus** [merikan/dotfiles#1]
Hi, we just wanted to let you know that you are still linking to the old Homebrew Cask homepage (`caskroom.io`) in [`Brewfile`](https://github.com/merikan/dotfiles/blob/88a50501b4bbaf1fbbbbec157ddcd1a576b66b62/brew/Brewfile). This domain expired a few years ago and is not controlled by Homebrew anymore.

When you get a chance, please update the link to https://brew.sh/ or https://formulae.brew.sh/cask/.

Thank you,
the Homebrew team.

**Comment by merikan** [comment]
Thanks for letting me know. Fixed.
